# Generated by Django 4.0.5 on 2022-06-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_artwork_canvas_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
