# Generated by Django 4.0.5 on 2022-07-01 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('start_date', models.DateField(help_text='YYYY-MM-DD')),
                ('end_date', models.DateField(help_text='YYYY-MM-DD')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='exhibition/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.artist')),
                ('artworks', models.ManyToManyField(to='collection.artwork')),
            ],
        ),
    ]
