# Generated by Django 4.0.5 on 2022-06-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_alter_exhibition_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='end_date',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='start_date',
            field=models.DateField(help_text='YYYY-MM-DD'),
        ),
    ]
