# Generated by Django 4.0.5 on 2022-06-29 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0003_alter_exhibition_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='poster',
        ),
    ]
