# Generated by Django 4.0.5 on 2022-06-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0004_remove_exhibition_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='exhibition/'),
        ),
    ]
